name: Deploy devops-app

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: get short commit tag
        run: echo "short_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/devops-app:${{ env.short_tag }}
            ${{ vars.DOCKER_USERNAME }}/devops-app:latest
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINUX_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.PROD_IP }} >> ~/.ssh/known_hosts
        
      - name: Deploy to Prod
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.PROD_IP }} << EOF
            cd /home/ubuntu/app
            docker compose restart
          EOF

      
      